# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration

PreCommit:
  CaseConflicts:
    enabled: false
  Brakeman:
    enabled: true
    quiet: false
  RuboCop:
    enabled: true
    quiet: false
    on_warn: fail
  TrailingWhitespace:
    enabled: true
    quiet: false
    exclude:
      - '**/*.md'

PrePush:
  RailsSchemaUpToDate:
    enabled: true
    quiet: false
  RSpec:
    enabled: true
    quiet: false
  BundleAudit:
    enabled: true
    quiet: false
  Fasterer:
    enabled: true
    quiet: false

PostMerge:
  RuboCop:
    enabled: true
    quiet: false
    on_warn: fail
