# frozen_string_literal: true

# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2020 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# See https://github.com/ankane/blazer#readme for more info about this config file

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# Create audits
audit: <%= Setting.true? :blazer_log_queries %>

# Enable anomaly detection; note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: trend / r

# Enable forecasting; note: with trend, time series are sent to https://trendapi.org
# forecasting: trend

# Enable map
<% if ENV[ 'MAPBOX_ACCESS_TOKEN' ].present? %>
mapbox_access_token: <%= ENV[ 'MAPBOX_ACCESS_TOKEN' ] %>
<% end %>

# If we're in dev environment, allow fallback to main database details
<% database_url = ENV[ 'BLAZER_DATABASE_URL' ].presence %>
<% database_url ||= ENV[ 'DATABASE_URL' ] if Rails.env.development? %>

data_sources:
  shinycms:
    url: <%= database_url %>

    smart_variables:
      device_type: "select '%' as id, 'all' as label union select distinct device_type as id, device_type as label from ahoy_visits order by label"
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      user_id: "/admin/users/{value}"

    smart_columns:
      user_id: "SELECT id, name FROM users WHERE id IN {value}"

    # statement timeout, in seconds - none by default
    # timeout: 15

    # caching settings, can greatly improve speed - off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety - not necessary if you use a read-only user - true by default
    # use_transaction: false

time_zone: <%= Rails.application.config.time_zone %>

# Email to send checks from
from_email: <%= Setting.get :site_email %>

# Display-name method
user_name: username

# Custom before_action to use for auth (defined in ApplicationController)
before_action_method: current_user_can_view_charts?
