AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
CheckSaveReturnValueCheck: { }
CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
HashSyntaxCheck: { }
# This was a data migration, not seed data
IsolateSeedDataCheck: { ignored_files: 'db/migrate/20201004150130_change_comment_author_to_polymorphic\.rb' }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
#MoveCodeIntoModelCheck: { use_count: 2 }   # 2
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
# Exemptions are: the method used to control access to Blazer (set in config/blazer.yml), and two methods that change default Devise behaviour
RemoveUnusedMethodsInControllersCheck: { except_methods: [ 'ApplicationController#current_user_can_view_charts?', 'MainController#after_sign_in_path_for', 'RegistrationsController#after_update_path_for' ] }
#RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }      # 10
#RemoveUnusedMethodsInModelsCheck: { except_methods: [] }       # 12
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
#ReplaceInstanceVariableWithLocalVariableCheck: { }  # 64
RestrictAutoGeneratedRoutesCheck: { }
#SimplifyRenderInControllersCheck: { }  # 21
#SimplifyRenderInViewsCheck: { }        # 40
## UseBeforeFilterCheck: { customize_count: 2 }   # 14
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
