AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
CheckSaveReturnValueCheck: { }
CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
HashSyntaxCheck: { }
#IsolateSeedDataCheck: { }  # 2
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
## LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
#MoveCodeIntoModelCheck: { use_count: 2 }   # 2
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
#RemoveUnusedMethodsInControllersCheck: { except_methods: [] }  # 3
#RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }      # 10
#RemoveUnusedMethodsInModelsCheck: { except_methods: [] }       # 12
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
#ReplaceInstanceVariableWithLocalVariableCheck: { }  # 64
RestrictAutoGeneratedRoutesCheck: { }
#SimplifyRenderInControllersCheck: { }  # 21
#SimplifyRenderInViewsCheck: { }        # 40
## UseBeforeFilterCheck: { customize_count: 2 }   # 14
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
#UseQueryAttributeCheck: { }  # 5
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
