# frozen_string_literal: true

# ShinyNewsletters plugin for ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2020 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Sidekiq configuration, for production mailer jobs
production:
  :concurrency: 3
  :queues:
    - shinycms_production_mailers
    - shinycms_production_active_storage_analysis
