---
Setting_1:
  id: 1
  name: admin_ip_list
  description: IP addresses allowed to access admin area (comma-separated)
  level: site
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &1 2020-04-24 19:52:33.357370000 Z
    zone: &2 !ruby/object:ActiveSupport::TimeZone
      name: Etc/UTC
    time: *1
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &3 2020-04-24 19:52:33.357370000 Z
    zone: *2
    time: *3
Setting_2:
  id: 2
  name: all_comment_notifications_email
  description: Set this to an email address to receive a notification for every comment
    posted on the site
  level: site
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &4 2020-04-24 19:52:33.402908000 Z
    zone: *2
    time: *4
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &5 2020-04-24 19:52:33.402908000 Z
    zone: *2
    time: *5
Setting_3:
  id: 3
  name: allowed_to_comment
  description: Lowest-ranking user-type (Anonymous/Pseudonymous/Authenticated/None)
    that is allowed to post comments
  level: site
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &6 2020-04-24 19:52:33.413352000 Z
    zone: *2
    time: *6
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &7 2020-04-24 19:52:33.413352000 Z
    zone: *2
    time: *7
Setting_4:
  id: 4
  name: default_page
  description: Default top-level page (either its name or its slug)
  level: site
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &8 2020-04-24 19:52:33.429392000 Z
    zone: *2
    time: *8
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &9 2020-04-24 19:52:33.429392000 Z
    zone: *2
    time: *9
Setting_5:
  id: 5
  name: default_section
  description: Default top-level section (either its name or its slug)
  level: site
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &10 2020-04-24 19:52:33.448401000 Z
    zone: *2
    time: *10
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &11 2020-04-24 19:52:33.448401000 Z
    zone: *2
    time: *11
Setting_6:
  id: 6
  name: post_login_redirect
  description: Where people are redirected after login, if no referer header
  level: admin
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &12 2020-04-24 19:52:33.457446000 Z
    zone: *2
    time: *12
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &13 2020-04-24 19:52:33.457446000 Z
    zone: *2
    time: *13
Setting_7:
  id: 7
  name: recaptcha_comment_score
  description: Minimum score for reCAPTCHA V3 on anon/pseudonymous comments
  level: admin
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &14 2020-04-24 19:52:33.466609000 Z
    zone: *2
    time: *14
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &15 2020-04-24 19:52:33.466609000 Z
    zone: *2
    time: *15
Setting_8:
  id: 8
  name: recaptcha_registration_score
  description: Minimum score for reCAPTCHA V3 on user registration
  level: admin
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &16 2020-04-24 19:52:33.474564000 Z
    zone: *2
    time: *16
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &17 2020-04-24 19:52:33.474564000 Z
    zone: *2
    time: *17
Setting_9:
  id: 9
  name: tag_view
  description: "('cloud' or 'list')"
  level: user
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &18 2020-04-24 19:52:33.483066000 Z
    zone: *2
    time: *18
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &19 2020-04-24 19:52:33.483066000 Z
    zone: *2
    time: *19
Setting_10:
  id: 10
  name: theme_name
  description: ''
  level: site
  locked: false
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &20 2020-04-24 19:52:33.492204000 Z
    zone: *2
    time: *20
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &21 2020-04-24 19:52:33.492204000 Z
    zone: *2
    time: *21
Setting_11:
  id: 11
  name: track_opens
  description: Track email opens
  level: site
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &22 2020-04-24 19:52:33.501110000 Z
    zone: *2
    time: *22
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &23 2020-04-24 19:52:33.501110000 Z
    zone: *2
    time: *23
Setting_12:
  id: 12
  name: track_clicks
  description: Track email link-clicks
  level: site
  locked: true
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &24 2020-04-24 19:52:33.510655000 Z
    zone: *2
    time: *24
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: &25 2020-04-24 19:52:33.510655000 Z
    zone: *2
    time: *25
